"""add product match

Revision ID: 1c55b203f5c4
Revises: 930241fb0b6b
Create Date: 2025-11-23 08:47:34.867757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c55b203f5c4'
down_revision: Union[str, None] = '930241fb0b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productmatch',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competitor_sku', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'competitor_id', name='uq_product_match_product_competitor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productmatch')
    # ### end Alembic commands ###
